ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/beats/filebeat:7.10.0
#
#USER root
#RUN chmod go-w /usr/share/filebeat/filebeat.yml
#RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
#USER filebeat
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
